# Generated by Django 4.2.2 on 2024-06-15 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vault_tvl', models.FloatField()),
                ('max_bounty', models.FloatField()),
                ('total_paid', models.FloatField()),
                ('last_updated', models.DateField(auto_now=True)),
                ('vault_address', models.CharField(max_length=100)),
                ('program_overview', models.JSONField()),
                ('rewards_by_threat_level_json', models.JSONField()),
                ('optional_assets_in_scope_json', models.JSONField()),
                ('optional_impacts_in_scope_json', models.JSONField()),
                ('out_of_scope_json', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='BountyRewardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('bounty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bounties.bounty')),
            ],
        ),
        migrations.CreateModel(
            name='BountyReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat_level', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Low', max_length=100)),
                ('reward_start', models.FloatField(default=0.0)),
                ('reward_end', models.FloatField(default=0.0)),
                ('bounty_reward_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bounties.bountyrewardcategory')),
            ],
        ),
        migrations.CreateModel(
            name='BountyImpactInScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat_level', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Low', max_length=100)),
                ('description', models.TextField()),
                ('bounty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bounties.bounty')),
            ],
        ),
        migrations.CreateModel(
            name='BountyAssetInScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('bounty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bounties.bounty')),
            ],
        ),
    ]
