# Generated by Django 5.0.6 on 2024-06-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='owner_address',
            field=models.CharField(default='empty', max_length=100),
        ),
    ]
