# Generated by Django 4.2.2 on 2024-06-15 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bounties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bountyimpactinscope',
            old_name='description',
            new_name='impact',
        ),
    ]
