# Generated by Django 4.2.2 on 2024-06-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounties', '0002_rename_description_bountyimpactinscope_impact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bounty',
            name='optional_assets_in_scope_json',
        ),
        migrations.RemoveField(
            model_name='bounty',
            name='optional_impacts_in_scope_json',
        ),
        migrations.RemoveField(
            model_name='bounty',
            name='out_of_scope_json',
        ),
        migrations.RemoveField(
            model_name='bounty',
            name='program_overview',
        ),
        migrations.RemoveField(
            model_name='bounty',
            name='rewards_by_threat_level_json',
        ),
        migrations.AddField(
            model_name='bounty',
            name='optional_assets_in_scope_html',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='bounty',
            name='optional_impacts_in_scope_html',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='bounty',
            name='out_of_scope_html',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='bounty',
            name='program_overview_html',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='bounty',
            name='rewards_by_threat_level_html',
            field=models.TextField(default=''),
        ),
    ]
