# Generated by Django 4.2.2 on 2024-06-19 04:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bounties', '0003_remove_bounty_optional_assets_in_scope_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
