# Generated by Django 4.2.2 on 2024-06-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounties', '0004_alter_bounty_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
