# Generated by Django 4.2.2 on 2024-06-19 05:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bounties', '0006_alter_bounty_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
