# Generated by Django 4.2.2 on 2024-06-19 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bounties', '0007_alter_bounty_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bountyassetinscope',
            name='bounty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='bounties.bounty'),
        ),
        migrations.AlterField(
            model_name='bountyimpactinscope',
            name='bounty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impacts', to='bounties.bounty'),
        ),
        migrations.AlterField(
            model_name='bountyreward',
            name='bounty_reward_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='bounties.bountyrewardcategory'),
        ),
        migrations.AlterField(
            model_name='bountyrewardcategory',
            name='bounty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='bounties.bounty'),
        ),
    ]
