# Generated by Django 4.2.2 on 2024-06-20 17:23

import bounties.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bounties', '0008_alter_bountyassetinscope_bounty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BountyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.TextField(default='')),
                ('address', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to=bounties.models.bounty_report_path)),
                ('bounty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='bounties.bounty')),
            ],
        ),
    ]
