# Generated by Django 4.2.2 on 2024-06-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounties', '0009_bountyreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bountyreport',
            name='address',
        ),
        migrations.AddField(
            model_name='bounty',
            name='owner_address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bountyreport',
            name='owner_address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
