# Generated by Django 4.2.2 on 2024-06-22 22:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bounties', '0010_remove_bountyreport_address_bounty_owner_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bountyreport',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
