# Generated by Django 4.2.2 on 2024-06-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounties', '0011_alter_bountyreport_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
