# Generated by Django 4.2.2 on 2024-06-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounties', '0012_bounty_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='bountyreport',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
